import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ConfigProvider } from 'antd'
import ptBR from 'antd/locale/pt_BR'

import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'

const roboto = Roboto({ subsets: ['cyrillic'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <ConfigProvider locale={ptBR}>{children}</ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
