import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'
// import StyledComponentsRegistry from '@/lib/AntdRegistry'

const roboto = Roboto({ subsets: ['cyrillic'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        {/* <StyledComponentsRegistry>{children}</StyledComponentsRegistry> */}
      </body>
    </html>
  )
}
